### ISSUE TITLE
I strongly suggest to speed it up.Because it's really very slow to memory/db store

### ISSUE THREAD

**Issue by yalishizhude** [valery-barysok/session-file-store#34] opened 2016-03-06 15:56 UTC

**Comment by valery-barysok** [comment] 2016-03-06 16:42
Please, describe your conditions and requirements because it's really very slow say nothing.

**Comment by yalishizhude** [comment] 2016-03-07 06:35
I find the method,but don't know the reason and I pull request

**Comment by valery-barysok** [comment] 2016-03-07 14:18
Thanks.
I looked at your PR and I have no idea why it has any performance issue in your case. It needs additional investigation to understand "why?!" Can you provide OS version, node version, conditions under which you launch your application and basic application that reproduce your issue.

**Comment by valery-barysok** [comment] 2016-04-02 19:28
So I closed this issue. There are not enough details for reproduce it and no one else report about it. thanks.

**Closed by valery-barysok** 2016-04-02 19:28 UTC

**Comment by yalishizhude** [comment] 2016-04-05 07:02
ok,thanks~
When I have time I'd like to research this issue~
